/*
  THIS FILE TO BE SOLELY USED AS AN EXAMPLE, AS IT HAS BEEN GENERATED BY AI.
 */

// 1. Define an interface for the component's configuration or props
export interface ButtonConfig {
  text: string;
  variant?: 'primary' | 'secondary'; // Optional property
  onClick: () => void;
}

// 2. Implement the component logic inside a class or function
export class ButtonComponent {
  private element: HTMLButtonElement;

  constructor(private config: ButtonConfig) {
    this.element = document.createElement('button');
    this.init();
  }

  private init(): void {
    this.element.innerText = this.config.text;
    this.element.className = `btn-${this.config.variant || 'primary'}`;
    this.element.addEventListener('click', this.config.onClick);
  }

  // Export a method to attach the component to the DOM
  public mount(parent: HTMLElement): void {
    parent.appendChild(this.element);
  }
}
